package com.vvtech.aiassistant.features.assistant_tasks

import java.io.File
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class AssistantTaskConversationLifecycleHandlerGuardTest {
    @Test
    fun viewModelDelegatesTaskConversationLifecycleWork() {
        val viewModel = File("src/main/java/com/vvtech/aiassistant/features/assistant/AssistantViewModel.kt")
            .readText()
        val facade = File("src/main/java/com/vvtech/aiassistant/features/assistant_facade/AssistantViewModelTaskSessionFacades.kt")
            .readText()
        val oldHandler =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_session/AssistantTaskConversationLifecycleHandler.kt")
        val handler =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/AssistantTaskConversationLifecycleHandler.kt")
                .readText(Charsets.UTF_8)
        val backgroundPauseReducer =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationBackgroundPauseReducer.kt")
                .readText(Charsets.UTF_8)
        val backgroundPauseStateHolder =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationBackgroundPauseStateHolder.kt")
                .readText(Charsets.UTF_8)
        val lifecycleStateAccess =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/AssistantTaskConversationLifecycleStateAccess.kt")
                .readText(Charsets.UTF_8)
        val exitResetController =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationExitResetController.kt")
                .readText(Charsets.UTF_8)
        val handlerGraph =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_lifecycle/AssistantViewModelHandlerGraph.kt")
                .readText()
        val listLoadUseCase =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationListLoadUseCase.kt")
                .readText()
        val listLoadController =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationListLoadController.kt")
                .readText(Charsets.UTF_8)
        val interruptUseCase =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationInterruptUseCase.kt")
                .readText()
        val interruptController =
            File("src/main/java/com/vvtech/aiassistant/features/assistant_tasks/TaskConversationInterruptController.kt")
                .readText(Charsets.UTF_8)

        assertFalse(oldHandler.exists())
        assertTrue(viewModel.contains("features.assistant_tasks.AssistantTaskConversationLifecycleHandler"))
        assertFalse(viewModel.contains("AssistantTaskConversationLifecycleDeps("))
        assertFalse(viewModel.contains("AssistantTaskConversationLifecycleCallbacks("))
        assertFalse(viewModel.contains("accountIdProvider = { AccountIdentityProvider.accountId }"))
        assertTrue(handlerGraph.contains("AssistantTaskConversationLifecycleDeps("))
        assertTrue(handlerGraph.contains("AssistantTaskConversationLifecycleCallbacks("))
        assertTrue(handlerGraph.contains("val lifecycleStateAccess = AssistantTaskConversationLifecycleStateAccess("))
        assertTrue(handlerGraph.contains("TaskRestoreStateHolder(viewModel.conversationList)"))
        assertTrue(handlerGraph.contains("TaskConversationExitResetStateReader(viewModel.internalUiState)"))
        assertTrue(handlerGraph.contains("TaskConversationBackgroundPauseStateHolder(viewModel.internalUiState)"))
        assertTrue(handlerGraph.contains("TaskConversationListLoadStateHolder("))
        assertTrue(handlerGraph.contains("stateAccess = lifecycleStateAccess"))
        assertTrue(handlerGraph.contains("TaskConversationListLoadUseCase(viewModel.repository)"))
        assertTrue(handlerGraph.contains("TaskConversationInterruptUseCase(viewModel.repository)"))
        assertTrue(handlerGraph.contains("accountIdProvider = { AccountIdentityProvider.accountId }"))
        assertFalse(viewModel.contains("AssistantTaskConversationLifecycleHandler(this)"))
        assertFalse(viewModel.contains("taskConversationLifecycleHandler.resetForNewEntry(reason)"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.resetForNewEntry(reason)"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.interruptForUserClose(reason)"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.pauseForBackground()"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.pauseAndResetLocalUi(reason, reloadConversations)"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.loadConversations(reason)"))
        assertTrue(facade.contains("taskConversationLifecycleHandler.returnToHomeFromResultPage()"))

        assertFalse(viewModel.contains("repository.interruptConversation("))
        assertFalse(viewModel.contains("repository.getConversations("))
        assertFalse(viewModel.contains("withResolvedStatus(detail)"))
        assertFalse(viewModel.contains("已暂停，返回后可继续"))

        assertTrue(handler.contains("AssistantTaskConversationLifecycleDeps"))
        assertTrue(handler.contains("AssistantTaskConversationLifecycleCallbacks"))
        assertTrue(handler.contains("stateAccess: AssistantTaskConversationLifecycleStateAccess"))
        assertFalse(handler.contains("AssistantViewModel"))
        assertFalse(handler.contains("private val viewModel"))
        assertFalse(handler.contains("viewModel."))
        assertFalse(handler.contains("androidx.lifecycle.viewModelScope"))
        assertFalse(handler.contains("MutableStateFlow<Index9AssistantUiState>"))
        assertFalse(handler.contains("MutableStateFlow<List<ConversationListItem>>"))
        assertFalse(handler.contains("MutableStateFlow<Boolean>"))
        assertFalse(handler.contains("MutableStateFlow<String?>"))
        assertFalse(handler.contains("repository.interruptConversation("))
        assertFalse(handler.contains("reason.equals(\"reset_task_flow\""))
        assertFalse(handler.contains("\"USER_INTERRUPTED\""))
        assertFalse(handler.contains("repository.getConversations("))
        assertFalse(handler.contains("repository.getConversation("))
        assertFalse(handler.contains("TaskConversationListStatusReducer.resolveStatuses"))
        assertTrue(handler.contains("TaskConversationInterruptController("))
        assertFalse(handler.contains("TaskRestoreStateHolder(deps.conversationList)"))
        assertFalse(handler.contains("TaskRestoreStateHolder("))
        assertTrue(handler.contains("taskRestoreStateHolder = deps.stateAccess.taskRestoreStateHolder"))
        assertTrue(handler.contains("interruptController.interruptForUserClose(reason)"))
        assertFalse(handler.contains("conversationInterruptUseCase.fallbackStatus(reason)"))
        assertFalse(handler.contains("conversationInterruptUseCase.interrupt("))
        assertTrue(interruptController.contains("deps.fallbackStatus(reason)"))
        assertTrue(interruptController.contains("deps.interrupt("))
        assertTrue(interruptController.contains("deps.taskRestoreStateHolder.updateConversationCardStatus("))
        assertFalse(interruptController.contains("TaskConversationListStatusReducer.updateStatus("))
        assertTrue(handler.contains("TaskConversationListLoadController("))
        assertTrue(handler.contains("listLoadController.loadConversations(reason)"))
        assertFalse(handler.contains("conversationListLoadUseCase.load("))
        assertTrue(handler.contains("stateHolder = deps.stateAccess.listLoadStateHolder"))
        assertTrue(listLoadController.contains("deps.load("))
        assertTrue(listLoadController.contains("callbacks.syncPendingExecutionErrorExitSessions()"))
        assertTrue(interruptUseCase.contains("repository.interruptConversation("))
        assertTrue(interruptUseCase.contains("reason.equals(ResetTaskFlowReason, ignoreCase = true)"))
        assertTrue(interruptUseCase.contains("\"RUNNING\""))
        assertTrue(interruptUseCase.contains("\"USER_INTERRUPTED\""))
        assertTrue(listLoadUseCase.contains("repository.getConversations(accountId)"))
        assertFalse(listLoadUseCase.contains("repository.getConversation("))
        assertFalse(listLoadUseCase.contains("TaskConversationListStatusReducer.resolveStatuses"))
        assertFalse(listLoadUseCase.contains("messagesJson"))
        assertTrue(handler.contains("accountIdProvider: () -> String"))
        assertTrue(handler.contains("accountIdProvider = deps.accountIdProvider"))
        assertTrue(listLoadController.contains("deps.accountIdProvider()"))
        assertFalse(handler.contains("AccountIdentityProvider"))
        assertFalse(handler.contains("features.assistant.viewmodel.DefaultUserId"))
        assertFalse(handler.contains("DefaultUserId"))
        assertFalse(handler.contains("withResolvedStatus(detail)"))
        assertFalse(handler.contains("conversationList.value.map"))
        assertFalse(handler.contains("TaskConversationBackgroundPauseStateHolder(deps.uiState)"))
        assertFalse(handler.contains("TaskConversationBackgroundPauseStateHolder("))
        assertTrue(handler.contains("deps.stateAccess.backgroundPauseStateHolder.applyBackgroundPause()"))
        assertFalse(handler.contains("deps.uiState.update"))
        assertFalse(handler.contains("TaskConversationBackgroundPauseReducer.apply(it)"))
        assertTrue(handler.contains("TaskConversationExitResetController("))
        assertFalse(handler.contains("TaskConversationExitResetStateReader(deps.uiState)"))
        assertFalse(handler.contains("TaskConversationExitResetStateReader("))
        assertTrue(handler.contains("stateReader = deps.stateAccess.exitResetStateReader"))
        assertTrue(handler.contains("exitResetController.pauseAndResetLocalUi(reason, reloadConversations)"))
        assertFalse(handler.contains("VoicePauseSource.Background"))
        assertFalse(handler.contains("voicePauseFlagsFor("))
        assertFalse(handler.contains("apiAsrPartialText = null"))
        assertFalse(handler.contains("liveAssistantTranscript = null"))
        assertFalse(handler.contains("shouldPersistExecutionErrorOnTaskExit("))
        assertTrue(backgroundPauseReducer.contains("已暂停，返回后可继续"))
        assertTrue(backgroundPauseReducer.contains("voicePauseFlagsFor(VoicePauseSource.Background)"))
        assertTrue(backgroundPauseReducer.contains("apiAsrPartialText = null"))
        assertTrue(backgroundPauseReducer.contains("liveAssistantTranscript = null"))
        assertTrue(backgroundPauseStateHolder.contains("private val uiState: MutableStateFlow<Index9AssistantUiState>"))
        assertTrue(backgroundPauseStateHolder.contains("uiState.update"))
        assertTrue(backgroundPauseStateHolder.contains("TaskConversationBackgroundPauseReducer.apply(it)"))
        assertTrue(lifecycleStateAccess.contains("data class AssistantTaskConversationLifecycleStateAccess"))
        assertTrue(lifecycleStateAccess.contains("val taskRestoreStateHolder: TaskRestoreStateHolder"))
        assertTrue(lifecycleStateAccess.contains("val exitResetStateReader: TaskConversationExitResetStateReader"))
        assertTrue(lifecycleStateAccess.contains("val backgroundPauseStateHolder: TaskConversationBackgroundPauseStateHolder"))
        assertTrue(lifecycleStateAccess.contains("val listLoadStateHolder: TaskConversationListLoadStateHolder"))
        assertTrue(exitResetController.contains("shouldPersistExecutionErrorOnTaskExit("))
        assertTrue(exitResetController.contains("deps.stateReader.currentState()"))
        assertFalse(exitResetController.contains("MutableStateFlow<Index9AssistantUiState>"))
        assertFalse(exitResetController.contains("deps.uiState.value"))
        assertTrue(exitResetController.contains("deps.taskRestoreStateHolder.updateConversationCardStatus("))
        assertFalse(exitResetController.contains("TaskConversationListStatusReducer.updateStatus("))
        assertTrue(exitResetController.contains("loadConversations(\"vm_pause:\$reason\")"))
    }
}
