org.gradle.jvmargs=-Xms512m -Xmx5120m -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=384m -Dfile.encoding=UTF-8
org.gradle.workers.max=2
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.incremental.useClasspathSnapshot=false
volcTtsSpeaker=zh_male_taocheng_uranus_bigtts
